package com.joyveb.gens.jpa.mapper;

import com.joyveb.gens.jpa.model.ParaGameinfo;
import com.joyveb.gens.jpa.model.ParaGameinfoExample;
import com.joyveb.gens.jpa.model.ParaGameinfoKey;
import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ParaGameinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    int countByExample(ParaGameinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    int deleteByExample(ParaGameinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    @Delete({
        "delete from T_PARA_GAMEINFO",
        "where LTYPE = #{ltype,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(ParaGameinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    @Insert({
        "insert into T_PARA_GAMEINFO (LTYPE, GAMENAME, ",
        "STATUS, STARTSALETIME, ",
        "ENDSALETIME, AHEADCLOSETIME, ",
        "EXPIREDDATES, DRAWPERIOD, ",
        "DRAWTIMES)",
        "values (#{ltype,jdbcType=VARCHAR}, #{gamename,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=DECIMAL}, #{startsaletime,jdbcType=VARCHAR}, ",
        "#{endsaletime,jdbcType=VARCHAR}, #{aheadclosetime,jdbcType=DECIMAL}, ",
        "#{expireddates,jdbcType=DECIMAL}, #{drawperiod,jdbcType=DECIMAL}, ",
        "#{drawtimes,jdbcType=DECIMAL})"
    })
    int insert(ParaGameinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    int insertSelective(ParaGameinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    List<ParaGameinfo> selectByExample(ParaGameinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "LTYPE, GAMENAME, STATUS, STARTSALETIME, ENDSALETIME, AHEADCLOSETIME, EXPIREDDATES, ",
        "DRAWPERIOD, DRAWTIMES",
        "from T_PARA_GAMEINFO",
        "where LTYPE = #{ltype,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ParaGameinfo selectByPrimaryKey(ParaGameinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ParaGameinfo record, @Param("example") ParaGameinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ParaGameinfo record, @Param("example") ParaGameinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ParaGameinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    @Update({
        "update T_PARA_GAMEINFO",
        "set GAMENAME = #{gamename,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=DECIMAL},",
          "STARTSALETIME = #{startsaletime,jdbcType=VARCHAR},",
          "ENDSALETIME = #{endsaletime,jdbcType=VARCHAR},",
          "AHEADCLOSETIME = #{aheadclosetime,jdbcType=DECIMAL},",
          "EXPIREDDATES = #{expireddates,jdbcType=DECIMAL},",
          "DRAWPERIOD = #{drawperiod,jdbcType=DECIMAL},",
          "DRAWTIMES = #{drawtimes,jdbcType=DECIMAL}",
        "where LTYPE = #{ltype,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ParaGameinfo record);

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_PARA_GAMEINFO
    */
    int sumByExample(ParaGameinfoExample example);

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_PARA_GAMEINFO
    */
    List<HashMap> groupByExample(ParaGameinfoExample example);
}