package com.joyveb.gens.core.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CoreLotoValiabl implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.CASKEY
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String caskey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.PACKAGEID
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String packageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.MESSAGEID
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String messageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.ORDERNO
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.MERCHANTID
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.LOGICCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String logiccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.CITYCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.SELLPERIOD
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private BigDecimal sellperiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.VALIDPERIOD
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private BigDecimal validperiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.RUNCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private Integer runcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.SELLDATETIME
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private Date selldatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.BETNUM
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private Integer betnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.SELLWAY
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String sellway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.DRAWWAY
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String drawway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.CODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.WITHDRAW
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String withdraw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.IDCARD
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.MOBILECODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String mobilecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.PHONECARDNO
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String phonecardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.PHONECARDPASSWORD
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String phonecardpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.SELLPERSONID
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String sellpersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.CHECKCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String checkcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.CREATEDATE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.TICKETCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String ticketcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.UPDATEDATE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.PLAYTYPE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String playtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.RESULT
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private Short result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CORE_LOTO_VALIABL.FAILREASON
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private String failreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_CORE_LOTO_VALIABL
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.CASKEY
     *
     * @return the value of T_CORE_LOTO_VALIABL.CASKEY
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getCaskey() {
        return caskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.CASKEY
     *
     * @param caskey the value for T_CORE_LOTO_VALIABL.CASKEY
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setCaskey(String caskey) {
        this.caskey = caskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.PACKAGEID
     *
     * @return the value of T_CORE_LOTO_VALIABL.PACKAGEID
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getPackageid() {
        return packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.PACKAGEID
     *
     * @param packageid the value for T_CORE_LOTO_VALIABL.PACKAGEID
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setPackageid(String packageid) {
        this.packageid = packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.MESSAGEID
     *
     * @return the value of T_CORE_LOTO_VALIABL.MESSAGEID
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.MESSAGEID
     *
     * @param messageid the value for T_CORE_LOTO_VALIABL.MESSAGEID
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setMessageid(String messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.ORDERNO
     *
     * @return the value of T_CORE_LOTO_VALIABL.ORDERNO
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.ORDERNO
     *
     * @param orderno the value for T_CORE_LOTO_VALIABL.ORDERNO
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.MERCHANTID
     *
     * @return the value of T_CORE_LOTO_VALIABL.MERCHANTID
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.MERCHANTID
     *
     * @param merchantid the value for T_CORE_LOTO_VALIABL.MERCHANTID
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.LOGICCODE
     *
     * @return the value of T_CORE_LOTO_VALIABL.LOGICCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getLogiccode() {
        return logiccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.LOGICCODE
     *
     * @param logiccode the value for T_CORE_LOTO_VALIABL.LOGICCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setLogiccode(String logiccode) {
        this.logiccode = logiccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.CITYCODE
     *
     * @return the value of T_CORE_LOTO_VALIABL.CITYCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.CITYCODE
     *
     * @param citycode the value for T_CORE_LOTO_VALIABL.CITYCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.SELLPERIOD
     *
     * @return the value of T_CORE_LOTO_VALIABL.SELLPERIOD
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public BigDecimal getSellperiod() {
        return sellperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.SELLPERIOD
     *
     * @param sellperiod the value for T_CORE_LOTO_VALIABL.SELLPERIOD
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setSellperiod(BigDecimal sellperiod) {
        this.sellperiod = sellperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.VALIDPERIOD
     *
     * @return the value of T_CORE_LOTO_VALIABL.VALIDPERIOD
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public BigDecimal getValidperiod() {
        return validperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.VALIDPERIOD
     *
     * @param validperiod the value for T_CORE_LOTO_VALIABL.VALIDPERIOD
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setValidperiod(BigDecimal validperiod) {
        this.validperiod = validperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.RUNCODE
     *
     * @return the value of T_CORE_LOTO_VALIABL.RUNCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public Integer getRuncode() {
        return runcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.RUNCODE
     *
     * @param runcode the value for T_CORE_LOTO_VALIABL.RUNCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setRuncode(Integer runcode) {
        this.runcode = runcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.SELLDATETIME
     *
     * @return the value of T_CORE_LOTO_VALIABL.SELLDATETIME
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public Date getSelldatetime() {
        return selldatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.SELLDATETIME
     *
     * @param selldatetime the value for T_CORE_LOTO_VALIABL.SELLDATETIME
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setSelldatetime(Date selldatetime) {
        this.selldatetime = selldatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.BETNUM
     *
     * @return the value of T_CORE_LOTO_VALIABL.BETNUM
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public Integer getBetnum() {
        return betnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.BETNUM
     *
     * @param betnum the value for T_CORE_LOTO_VALIABL.BETNUM
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setBetnum(Integer betnum) {
        this.betnum = betnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.SELLWAY
     *
     * @return the value of T_CORE_LOTO_VALIABL.SELLWAY
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getSellway() {
        return sellway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.SELLWAY
     *
     * @param sellway the value for T_CORE_LOTO_VALIABL.SELLWAY
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setSellway(String sellway) {
        this.sellway = sellway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.DRAWWAY
     *
     * @return the value of T_CORE_LOTO_VALIABL.DRAWWAY
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getDrawway() {
        return drawway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.DRAWWAY
     *
     * @param drawway the value for T_CORE_LOTO_VALIABL.DRAWWAY
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setDrawway(String drawway) {
        this.drawway = drawway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.CODE
     *
     * @return the value of T_CORE_LOTO_VALIABL.CODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.CODE
     *
     * @param code the value for T_CORE_LOTO_VALIABL.CODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.WITHDRAW
     *
     * @return the value of T_CORE_LOTO_VALIABL.WITHDRAW
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getWithdraw() {
        return withdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.WITHDRAW
     *
     * @param withdraw the value for T_CORE_LOTO_VALIABL.WITHDRAW
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setWithdraw(String withdraw) {
        this.withdraw = withdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.IDCARD
     *
     * @return the value of T_CORE_LOTO_VALIABL.IDCARD
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.IDCARD
     *
     * @param idcard the value for T_CORE_LOTO_VALIABL.IDCARD
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.MOBILECODE
     *
     * @return the value of T_CORE_LOTO_VALIABL.MOBILECODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getMobilecode() {
        return mobilecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.MOBILECODE
     *
     * @param mobilecode the value for T_CORE_LOTO_VALIABL.MOBILECODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setMobilecode(String mobilecode) {
        this.mobilecode = mobilecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.PHONECARDNO
     *
     * @return the value of T_CORE_LOTO_VALIABL.PHONECARDNO
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getPhonecardno() {
        return phonecardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.PHONECARDNO
     *
     * @param phonecardno the value for T_CORE_LOTO_VALIABL.PHONECARDNO
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setPhonecardno(String phonecardno) {
        this.phonecardno = phonecardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.PHONECARDPASSWORD
     *
     * @return the value of T_CORE_LOTO_VALIABL.PHONECARDPASSWORD
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getPhonecardpassword() {
        return phonecardpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.PHONECARDPASSWORD
     *
     * @param phonecardpassword the value for T_CORE_LOTO_VALIABL.PHONECARDPASSWORD
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setPhonecardpassword(String phonecardpassword) {
        this.phonecardpassword = phonecardpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.SELLPERSONID
     *
     * @return the value of T_CORE_LOTO_VALIABL.SELLPERSONID
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getSellpersonid() {
        return sellpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.SELLPERSONID
     *
     * @param sellpersonid the value for T_CORE_LOTO_VALIABL.SELLPERSONID
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setSellpersonid(String sellpersonid) {
        this.sellpersonid = sellpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.CHECKCODE
     *
     * @return the value of T_CORE_LOTO_VALIABL.CHECKCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getCheckcode() {
        return checkcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.CHECKCODE
     *
     * @param checkcode the value for T_CORE_LOTO_VALIABL.CHECKCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setCheckcode(String checkcode) {
        this.checkcode = checkcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.CREATEDATE
     *
     * @return the value of T_CORE_LOTO_VALIABL.CREATEDATE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.CREATEDATE
     *
     * @param createdate the value for T_CORE_LOTO_VALIABL.CREATEDATE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.TICKETCODE
     *
     * @return the value of T_CORE_LOTO_VALIABL.TICKETCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getTicketcode() {
        return ticketcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.TICKETCODE
     *
     * @param ticketcode the value for T_CORE_LOTO_VALIABL.TICKETCODE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setTicketcode(String ticketcode) {
        this.ticketcode = ticketcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.UPDATEDATE
     *
     * @return the value of T_CORE_LOTO_VALIABL.UPDATEDATE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.UPDATEDATE
     *
     * @param updatedate the value for T_CORE_LOTO_VALIABL.UPDATEDATE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.PLAYTYPE
     *
     * @return the value of T_CORE_LOTO_VALIABL.PLAYTYPE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getPlaytype() {
        return playtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.PLAYTYPE
     *
     * @param playtype the value for T_CORE_LOTO_VALIABL.PLAYTYPE
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setPlaytype(String playtype) {
        this.playtype = playtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.RESULT
     *
     * @return the value of T_CORE_LOTO_VALIABL.RESULT
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public Short getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.RESULT
     *
     * @param result the value for T_CORE_LOTO_VALIABL.RESULT
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setResult(Short result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CORE_LOTO_VALIABL.FAILREASON
     *
     * @return the value of T_CORE_LOTO_VALIABL.FAILREASON
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public String getFailreason() {
        return failreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CORE_LOTO_VALIABL.FAILREASON
     *
     * @param failreason the value for T_CORE_LOTO_VALIABL.FAILREASON
     *
     * @mbggenerated Tue Jun 25 19:16:32 CST 2013
     */
    public void setFailreason(String failreason) {
        this.failreason = failreason;
    }
}