package com.joyveb.redis.bean;

import java.util.Date;

public class ParaDrawnumber extends ParaDrawnumberKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.YEAR
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.STARTDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.ENDDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.STATUS
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.SALESTATUS
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Integer salestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.REALSTARTDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Date realstartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.REALENDDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Date realenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.CLOSESHAREDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Date closesharedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.CREATEDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.UPDATEDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.RUNSTATUS
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Short runstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.PROCESSSTATUS
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Integer processstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.CURRCDC
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Long currcdc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.MDATA1
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Long mdata1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.MDATA2
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Long mdata2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.MDATA3
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private String mdata3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.MDATA4
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private String mdata4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.MDATA5
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Date mdata5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.YEAR
     *
     * @return the value of T_PARA_DRAWNUMBER.YEAR
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.YEAR
     *
     * @param year the value for T_PARA_DRAWNUMBER.YEAR
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.STARTDATE
     *
     * @return the value of T_PARA_DRAWNUMBER.STARTDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.STARTDATE
     *
     * @param startdate the value for T_PARA_DRAWNUMBER.STARTDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.ENDDATE
     *
     * @return the value of T_PARA_DRAWNUMBER.ENDDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.ENDDATE
     *
     * @param enddate the value for T_PARA_DRAWNUMBER.ENDDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.STATUS
     *
     * @return the value of T_PARA_DRAWNUMBER.STATUS
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.STATUS
     *
     * @param status the value for T_PARA_DRAWNUMBER.STATUS
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.SALESTATUS
     *
     * @return the value of T_PARA_DRAWNUMBER.SALESTATUS
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Integer getSalestatus() {
        return salestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.SALESTATUS
     *
     * @param salestatus the value for T_PARA_DRAWNUMBER.SALESTATUS
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setSalestatus(Integer salestatus) {
        this.salestatus = salestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.REALSTARTDATE
     *
     * @return the value of T_PARA_DRAWNUMBER.REALSTARTDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Date getRealstartdate() {
        return realstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.REALSTARTDATE
     *
     * @param realstartdate the value for T_PARA_DRAWNUMBER.REALSTARTDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setRealstartdate(Date realstartdate) {
        this.realstartdate = realstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.REALENDDATE
     *
     * @return the value of T_PARA_DRAWNUMBER.REALENDDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Date getRealenddate() {
        return realenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.REALENDDATE
     *
     * @param realenddate the value for T_PARA_DRAWNUMBER.REALENDDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setRealenddate(Date realenddate) {
        this.realenddate = realenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.CLOSESHAREDATE
     *
     * @return the value of T_PARA_DRAWNUMBER.CLOSESHAREDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Date getClosesharedate() {
        return closesharedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.CLOSESHAREDATE
     *
     * @param closesharedate the value for T_PARA_DRAWNUMBER.CLOSESHAREDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setClosesharedate(Date closesharedate) {
        this.closesharedate = closesharedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.CREATEDATE
     *
     * @return the value of T_PARA_DRAWNUMBER.CREATEDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.CREATEDATE
     *
     * @param createdate the value for T_PARA_DRAWNUMBER.CREATEDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.UPDATEDATE
     *
     * @return the value of T_PARA_DRAWNUMBER.UPDATEDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.UPDATEDATE
     *
     * @param updatedate the value for T_PARA_DRAWNUMBER.UPDATEDATE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.RUNSTATUS
     *
     * @return the value of T_PARA_DRAWNUMBER.RUNSTATUS
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Short getRunstatus() {
        return runstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.RUNSTATUS
     *
     * @param runstatus the value for T_PARA_DRAWNUMBER.RUNSTATUS
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setRunstatus(Short runstatus) {
        this.runstatus = runstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.PROCESSSTATUS
     *
     * @return the value of T_PARA_DRAWNUMBER.PROCESSSTATUS
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Integer getProcessstatus() {
        return processstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.PROCESSSTATUS
     *
     * @param processstatus the value for T_PARA_DRAWNUMBER.PROCESSSTATUS
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setProcessstatus(Integer processstatus) {
        this.processstatus = processstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.CURRCDC
     *
     * @return the value of T_PARA_DRAWNUMBER.CURRCDC
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Long getCurrcdc() {
        return currcdc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.CURRCDC
     *
     * @param currcdc the value for T_PARA_DRAWNUMBER.CURRCDC
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setCurrcdc(Long currcdc) {
        this.currcdc = currcdc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.MDATA1
     *
     * @return the value of T_PARA_DRAWNUMBER.MDATA1
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Long getMdata1() {
        return mdata1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.MDATA1
     *
     * @param mdata1 the value for T_PARA_DRAWNUMBER.MDATA1
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setMdata1(Long mdata1) {
        this.mdata1 = mdata1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.MDATA2
     *
     * @return the value of T_PARA_DRAWNUMBER.MDATA2
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Long getMdata2() {
        return mdata2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.MDATA2
     *
     * @param mdata2 the value for T_PARA_DRAWNUMBER.MDATA2
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setMdata2(Long mdata2) {
        this.mdata2 = mdata2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.MDATA3
     *
     * @return the value of T_PARA_DRAWNUMBER.MDATA3
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public String getMdata3() {
        return mdata3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.MDATA3
     *
     * @param mdata3 the value for T_PARA_DRAWNUMBER.MDATA3
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setMdata3(String mdata3) {
        this.mdata3 = mdata3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.MDATA4
     *
     * @return the value of T_PARA_DRAWNUMBER.MDATA4
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public String getMdata4() {
        return mdata4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.MDATA4
     *
     * @param mdata4 the value for T_PARA_DRAWNUMBER.MDATA4
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setMdata4(String mdata4) {
        this.mdata4 = mdata4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.MDATA5
     *
     * @return the value of T_PARA_DRAWNUMBER.MDATA5
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Date getMdata5() {
        return mdata5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.MDATA5
     *
     * @param mdata5 the value for T_PARA_DRAWNUMBER.MDATA5
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setMdata5(Date mdata5) {
        this.mdata5 = mdata5;
    }
}