package com.joyveb.redis.bean;

import java.math.BigDecimal;

public class ParaDrawnumberKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.LTYPE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private Short ltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.IDRAWNUMBER
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private BigDecimal idrawnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_DRAWNUMBER.EDRAWNUMBER
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    private BigDecimal edrawnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.LTYPE
     *
     * @return the value of T_PARA_DRAWNUMBER.LTYPE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public Short getLtype() {
        return ltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.LTYPE
     *
     * @param ltype the value for T_PARA_DRAWNUMBER.LTYPE
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setLtype(Short ltype) {
        this.ltype = ltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.IDRAWNUMBER
     *
     * @return the value of T_PARA_DRAWNUMBER.IDRAWNUMBER
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public BigDecimal getIdrawnumber() {
        return idrawnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.IDRAWNUMBER
     *
     * @param idrawnumber the value for T_PARA_DRAWNUMBER.IDRAWNUMBER
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setIdrawnumber(BigDecimal idrawnumber) {
        this.idrawnumber = idrawnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_DRAWNUMBER.EDRAWNUMBER
     *
     * @return the value of T_PARA_DRAWNUMBER.EDRAWNUMBER
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public BigDecimal getEdrawnumber() {
        return edrawnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_DRAWNUMBER.EDRAWNUMBER
     *
     * @param edrawnumber the value for T_PARA_DRAWNUMBER.EDRAWNUMBER
     *
     * @mbggenerated Mon Jul 29 19:35:37 CST 2013
     */
    public void setEdrawnumber(BigDecimal edrawnumber) {
        this.edrawnumber = edrawnumber;
    }
}