package com.joyveb.gens.jpa.model;

public class ParaProperties extends ParaPropertiesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_PROPERTIES.VALUE
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_PROPERTIES.DES
     *
     * @mbggenerated
     */
    private String des;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_PROPERTIES.VALUE
     *
     * @return the value of T_PARA_PROPERTIES.VALUE
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_PROPERTIES.VALUE
     *
     * @param value the value for T_PARA_PROPERTIES.VALUE
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_PROPERTIES.DES
     *
     * @return the value of T_PARA_PROPERTIES.DES
     *
     * @mbggenerated
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_PROPERTIES.DES
     *
     * @param des the value for T_PARA_PROPERTIES.DES
     *
     * @mbggenerated
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_PROPERTIES
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ParaProperties other = (ParaProperties) that;
        return (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getDes() == null ? other.getDes() == null : this.getDes().equals(other.getDes()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_PROPERTIES
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getDes() == null) ? 0 : getDes().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_PROPERTIES
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", value=").append(value);
        sb.append(", des=").append(des);
        sb.append("]");
        return sb.toString();
    }
}