package com.joyveb.gens.jpa.model;

public class ParaPropertiesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_PROPERTIES.KEY
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_PROPERTIES.KEY
     *
     * @return the value of T_PARA_PROPERTIES.KEY
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_PROPERTIES.KEY
     *
     * @param key the value for T_PARA_PROPERTIES.KEY
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_PROPERTIES
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ParaPropertiesKey other = (ParaPropertiesKey) that;
        return (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_PROPERTIES
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_PROPERTIES
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", key=").append(key);
        sb.append("]");
        return sb.toString();
    }
}