package com.joyveb.gens.jpa.model;

public class ParaGameinfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_GAMEINFO.LTYPE
     *
     * @mbggenerated
     */
    private String ltype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_GAMEINFO.LTYPE
     *
     * @return the value of T_PARA_GAMEINFO.LTYPE
     *
     * @mbggenerated
     */
    public String getLtype() {
        return ltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_GAMEINFO.LTYPE
     *
     * @param ltype the value for T_PARA_GAMEINFO.LTYPE
     *
     * @mbggenerated
     */
    public void setLtype(String ltype) {
        this.ltype = ltype == null ? null : ltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ParaGameinfoKey other = (ParaGameinfoKey) that;
        return (this.getLtype() == null ? other.getLtype() == null : this.getLtype().equals(other.getLtype()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLtype() == null) ? 0 : getLtype().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_GAMEINFO
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ltype=").append(ltype);
        sb.append("]");
        return sb.toString();
    }
}