package com.joyveb.cassandra.dao;

import java.util.List;


public interface SimGameInfoDAO extends BaseCassandraDao<String, SimGameInfo>{

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SIM_GAMEINFO
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    void insert(SimGameInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SIM_GAMEINFO
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
//    List<SimGameInfo> selectByExample(SimGameInfo example);
    List<SimGameInfo> selectByExample(Example<String> example);
    List<SimGameInfo> findByPage(Example<String> example, int pagesize,
			String startKey, String endKey);
    Integer count(Example<String> example);
    
    void truncate();

    SimGameInfo selectByPrimaryKey(String key);
    
    void batchInsert(List<SimGameInfo> list);
    
    List<SimGameInfo> selectByExampleWithCQL(ExampleByCQL example);
    List<SimGameInfo> selectByCQL(String cql);
    
    public void delete(String key);
    
    public CassandraList<String, SimGameInfo> findByPages(Example<String> example, int pagesize,
			String startKey, String endKey);
}